# config file
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.5
        auth:
          username: mrmcaustin1
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
    # Step 1: Obtain repo from GH
    - checkout

    # Step 2: Create v-env and install dep.
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

    # Step 3: Run linter and tests
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator